class LiteLLMError(Exception):
    def __init__(self, status_code: int, message: str):
        self.status_code = status_code
        self.message = message
        super().__init__(f"[{status_code}] {message}")


class AuthenticationError(LiteLLMError): ...
class RateLimitError(LiteLLMError): ...
class BadRequestError(LiteLLMError): ...
class NotFoundError(LiteLLMError): ...
class ContentPolicyViolationError(LiteLLMError): ...
class ContextWindowExceededError(LiteLLMError): ...
class InternalServerError(LiteLLMError): ...
class TimeoutError(LiteLLMError): ...
class ServiceUnavailableError(LiteLLMError): ...
class UnknownProviderError(LiteLLMError): ...
